### ISSUE TITLE
Forbidden error when clicking on an ad and not logged in.  

### ISSUE THREAD

**Issue by romans127** [punkave/apostrophe-ads#1]
Greetings , 

I know the description said this module is in early stages of development.  I am curious if you have am idea as to how to correct the forbidden message that is displayed upon clicking on an ad when the user is not logged in

**Comment by kerrygilbert** [comment]
Good catch. I hadn't tested it logged out yet!

I am committing a fix for this issue now. Thanks.

**Comment by romans127** [comment]
Thank you,
Nice work by the way.

**Comment by kerrygilbert** [comment]
Thanks for submitting the issue! This should be all set now.
